### Get all customers
GET http://localhost:8832/api/customers HTTP/1.1
content-type: application/json

### Get a customer
GET http://localhost:8832/api/customers/5e08f7f5-ebb8-44b6-9c73-0c006ef57a77 HTTP/1.1
content-type: application/json

### Create a customer
POST http://localhost:8832/api/customers/ HTTP/1.1
content-type: application/json

{   
    "firstName": "Francisco",
    "lastName": "Beltrao",
    "email": "frbeltra@microsoft.com",
    "addresses": [
        {        
            "address": "My street 123",
            "zipCode": "1321",
            "city": "Amsterdam",
            "IsActual": true
        }]  
}

### Update a customer
PUT http://localhost:8832/api/customers/394a3a9b-654e-492f-8e0a-87c0cea9ba33 HTTP/1.1
content-type: application/json

{   
    "firstName": "Francisco",
    "lastName": "Beltrao",
    "email": "frbeltra@microsoft.com",
    "addresses": [
        {        
            "address": "My street 123",
            "zipCode": "1321",
            "city": "Amsterdam",
            "IsActual": true
        }]  
}


### Create order with VALID credit card
POST http://localhost:8832/api/orders HTTP/1.1
content-type: application/json

{   
    "customerId" : "394a3a9b-654e-492f-8e0a-87c0cea9ba33",
    "payment": {
        "creditCardType": "VISA",
        "creditCardNumber" : "31232131221321",
        "expirationMonth" : "12",
        "expirationYear" : "2020"
    },
    "items": [
        {
            "vendorId" : "d43a794c-d328-4669-9a87-6ed13df2823e",
            "productId" : "86beff90-3f8e-4d7d-9f99-1f495ae77698",
            "quantity" : "2",
            "unitPrice" : "10" 
        }
    ],
    "deliveryAddress": {        
            "address": "My street 123",
            "zipCode": "1321",
            "city": "Amsterdam",
            "IsActual": true
    }
}

### Create order with INVALID credit card
POST http://localhost:8832/api/orders HTTP/1.1
content-type: application/json

{   
    "customerId" : "394a3a9b-654e-492f-8e0a-87c0cea9ba33",
    "payment": {
        "creditCardType": "VISA",
        "creditCardNumber" : "31232131221321",
        "expirationMonth" : "12",
        "expirationYear" : "2010"
    },
    "items": [
        {
            "vendorId" : "d43a794c-d328-4669-9a87-6ed13df2823e",
            "productId" : "86beff90-3f8e-4d7d-9f99-1f495ae77698",
            "quantity" : "2",
            "unitPrice" : "10" 
        }
    ],
    "deliveryAddress": {        
            "address": "My street 456",
            "zipCode": "900",
            "city": "Zurich",
            "IsActual": true
    }
}

### Get order by id
GET http://localhost:8832/api/orders/cdac8ab2-2dd8-4348-a2dd-f8708bfde6fd HTTP/1.1


### Get pending orders
GET http://localhost:8832/api/orders/pending HTTP/1.1

### Get products in catalog
GET http://localhost:8832/api/products HTTP/1.1


### Get specific product in catalog
GET http://localhost:8832/api/products/e74032b9-5ca6-41ef-82ba-b0e6fab40ae6 HTTP/1.1