### Get all vendors
GET http://localhost:8307/api/vendors HTTP/1.1
content-type: application/json

### Create a vendor
POST http://localhost:8307/api/vendors/ HTTP/1.1
content-type: application/json

{   
    "name": "Vendor A",
    "address" :  
    {
            "address": "My street 123",
            "zipCode": "1321",
            "city": "Amsterdam",
            "isActual": true
    }
}

### Get a vendor
GET http://localhost:8307/api/vendors/de6b9761-b441-41b7-bb45-671db30ccb25 HTTP/1.1
content-type: application/json



### Update a vendor
PUT http://localhost:8307/api/vendors/de6b9761-b441-41b7-bb45-671db30ccb25 HTTP/1.1
content-type: application/json

{   
    "name": "Vendor A+1",
    "address" :  
    {
            "address": "My street 123",
            "zipCode": "1321",
            "city": "Amsterdam",
            "isActual": true
    }
}


### Gets vendor products
GET http://localhost:8307/api/vendors/de6b9761-b441-41b7-bb45-671db30ccb25/products HTTP/1.1
content-type: application/json


### Gets single vendor product
GET http://localhost:8307/api/vendors/de6b9761-b441-41b7-bb45-671db30ccb25/products/e74032b9-5ca6-41ef-82ba-b0e6fab40ae6 HTTP/1.1
content-type: application/json

### Create a product
POST http://localhost:8307/api/vendors/de6b9761-b441-41b7-bb45-671db30ccb25/products HTTP/1.1
content-type: application/json

{   
    "name": "Mayo",
    "price": 4,
    "enabled" : true,
    "membersOnly": false
}

### Update Mayo product
PUT http://localhost:8307/api/vendors/de6b9761-b441-41b7-bb45-671db30ccb25/products/e74032b9-5ca6-41ef-82ba-b0e6fab40ae6 HTTP/1.1
content-type: application/json

{   
    "name": "Mayo",
    "price": 5,
    "enabled" : true,
    "membersOnly": false
}


### Update Honey product
PUT http://localhost:8307/api/vendors/de6b9761-b441-41b7-bb45-671db30ccb25/products/5026869c-f300-4eed-88f9-aa89af990fe2 HTTP/1.1
content-type: application/json

{   
    "name": "Honey",
    "price": 1.5,
    "enabled" : true,
    "membersOnly": false
}
